<?php
/**
 * @file
 * The GTmetrix module
 */

/**
 * Implements hook_help().
 */
function gtmetrix_help($path, $arg) {
  switch ($path) {
    case "admin/help#gtmetrix":
      $output = '';
      $output .= '<h3>' . t('About') . '<h3>';
      $output .= '<p>' . t('The Gtmetrix module does') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Title of first use') . '</dt>';
      $output .= '<dd>' . t('Usage information') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function gtmetrix_menu() {
  $items = array();
  $items['admin/config/development/gtmetrix'] = array(
    'title' => 'Gtmetrix',
    'description' => 'Configuration for the GTmetrix module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gtmetrix_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'gtmetrix.admin.inc',
  );
  $items['gtmetrix'] = array(
    'title' => 'Gtmetrix',
    'page callback' => '_gtmetrix_page',
    'access arguments' => array('access gtmetrix content'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function gtmetrix_permission() {
  return array(
    'access gtmetrix content' => array(
      'title' => t('Access content for the Gtmetrix module'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function gtmetrix_block_info() {
  $blocks['gtmetrix'] = array(
    // The name that will appear in the block list.
    'info' => t('Gtmetrix'),
    // Default settings.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the content of the block
 */
function gtmetrix_block_view($delta = '') {
  switch ($delta) {
    case 'gtmetrix':
      $block['subject'] = t('Gtmetrix');
      if (user_access('access_content')) {
        // Retrieve data.
        $items = array();
        // Theme output.
        if (!empty($items)) {
          $block['content'] = theme('item_list', array(
            'items' => $items));
        }
        else {
          $block['content'] = t('No data.');
        }
      }
  }
  return $block;
}
